AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  niehs-sam

  Sample SAM Template for niehs-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        FileAddedEvent:
          Type: S3
          Properties:
            Bucket: !Ref ConversionS3
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: xls
      Policies:
          #S3CrudPolicy:
          S3FullAccessPolicy:
            BucketName: "niehs-excel-conversion" 
  ConversionS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "niehs-excel-conversion" 
  